# Generated by Django 3.0.4 on 2020-07-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.IntegerField(),
        ),
    ]
