# Generated by Django 3.0.4 on 2020-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTAPP', '0003_auto_20200712_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(max_length=400),
        ),
    ]
